Repository json-store-25/json-store-be, pull requests merged in 2025-04, with the labels that each got.

#34 feat: 기본 Dto, 예외 핸들러 개발
  src/main/java/deepdive/jsonstore/common/dto/BaseDto.java
  src/main/java/deepdive/jsonstore/common/dto/ErrorDto.java
  src/main/java/deepdive/jsonstore/common/dto/ResponseDto.java
  src/main/java/deepdive/jsonstore/common/exception/CustomException.java
  src/main/java/deepdive/jsonstore/common/exception/GlobalExceptionHandler.java
Labels: 💫 feat

#39 9 feat 주문 엔티티레포지토리 생성
  src/main/java/deepdive/jsonstore/domain/order/dto/OrderResponse.java
  src/main/java/deepdive/jsonstore/domain/order/model/Order.java
  src/main/java/deepdive/jsonstore/domain/order/model/OrderProduct.java
  src/main/java/deepdive/jsonstore/domain/order/model/OrderStatus.java
  src/main/java/deepdive/jsonstore/domain/order/repository/OrderRepository.java
  src/main/java/deepdive/jsonstore/domain/order/service/OrderValidationService.java
Labels: 💫 feat

#46 [FEAT] 상품 엔티티 및 리포지토리, 검증 서비스 추가
  src/main/java/deepdive/jsonstore/domain/product/dto/ActiveProductResponse.java
  src/main/java/deepdive/jsonstore/domain/product/model/Product.java
  src/main/java/deepdive/jsonstore/domain/product/repository/ProductRepository.java
  src/main/java/deepdive/jsonstore/domain/product/service/ProductValidationService.java
Labels: 💫 feat

#52 chore: ErrorResponse 변경, Exception 추기, JsonStoreErrorCode 추가
  src/main/java/deepdive/jsonstore/common/advice/GlobalExceptionHandler.java
  src/main/java/deepdive/jsonstore/common/dto/BaseDto.java
  src/main/java/deepdive/jsonstore/common/dto/ErrorDto.java
  src/main/java/deepdive/jsonstore/common/dto/ErrorResponse.java
  src/main/java/deepdive/jsonstore/common/dto/ResponseDto.java
  src/main/java/deepdive/jsonstore/common/entity/BaseEntity.java
  src/main/java/deepdive/jsonstore/common/exception/CommonException.java
  src/main/java/deepdive/jsonstore/common/exception/CustomException.java
  src/main/java/deepdive/jsonstore/common/exception/GlobalExceptionHandler.java
  src/main/java/deepdive/jsonstore/common/exception/JsonStoreErrorCode.java
  src/main/java/deepdive/jsonstore/common/exception/OrderException.java
  src/main/java/deepdive/jsonstore/domain/order/model/OrderProduct.java
Labels: ⚙️ chore

#65 feat : Member uid 필드 수정 MemberValidationService findByUid 추가
  src/main/java/deepdive/jsonstore/domain/member/model/Member.java
  src/main/java/deepdive/jsonstore/domain/member/repository/MemberRepository.java
  src/main/java/deepdive/jsonstore/domain/member/service/MemberValidationService.java
Labels: 💫 feat

#67 feat: fcm 토큰 저장 기능 추가
  build.gradle
  docker-compose.yml
  src/main/java/deepdive/jsonstore/JsonstoreApplication.java
  src/main/java/deepdive/jsonstore/common/config/FirebaseConfig.java
  src/main/java/deepdive/jsonstore/common/exception/JsonStoreErrorCode.java
  src/main/java/deepdive/jsonstore/domain/notification/controller/NotificationApiController.java
  src/main/java/deepdive/jsonstore/domain/notification/dto/FcmTokenRequest.java
  src/main/java/deepdive/jsonstore/domain/notification/dto/NotificationRequest.java
  src/main/java/deepdive/jsonstore/domain/notification/entity/Notification.java
  src/main/java/deepdive/jsonstore/domain/notification/entity/NotificationCategory.java
  src/main/java/deepdive/jsonstore/domain/notification/repository/NotificationRepository.java
  src/main/java/deepdive/jsonstore/domain/notification/service/NotificationService.java
  src/main/java/deepdive/jsonstore/domain/notification/service/NotificationValidationService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/static/css/style.css
  src/main/resources/static/firebase-messaging-sw.js
  src/main/resources/static/index.html
  src/main/resources/static/js/firebase-init.js
  src/main/resources/static/js/history-fetcher.js
  src/main/resources/static/js/register-token.js
  src/main/resources/static/js/send-notification.js
  src/test/java/deepdive/jsonstore/domain/notification/controller/NotificationApiControllerTest.java
  src/test/java/deepdive/jsonstore/domain/notification/service/NotificationServiceTest.java
Labels: 💫 feat, ✅ test

#72 11 feat 주문 생성기능 테스트 코드 작성
  src/main/java/deepdive/jsonstore/domain/order/dto/OrderRequest.java
  src/main/java/deepdive/jsonstore/domain/order/service/OrderService.java
  src/main/java/deepdive/jsonstore/domain/order/service/OrderValidationService.java
  src/test/java/deepdive/jsonstore/domain/order/service/OrderServiceTest.java
  src/test/java/deepdive/jsonstore/domain/order/service/OrderValidationServiceTest.java
Labels: ✅ test

#70 feat: 알림 전송 기능 추가
  src/main/java/deepdive/jsonstore/common/advice/GlobalExceptionHandler.java
  src/main/java/deepdive/jsonstore/common/config/FirebaseConfig.java
  src/main/java/deepdive/jsonstore/common/exception/JsonStoreErrorCode.java
  src/main/java/deepdive/jsonstore/common/exception/NotificationException.java
  src/main/java/deepdive/jsonstore/domain/notification/controller/NotificationApiController.java
  src/main/java/deepdive/jsonstore/domain/notification/dto/FcmTokenRequest.java
  src/main/java/deepdive/jsonstore/domain/notification/dto/NotificationRequest.java
  src/main/java/deepdive/jsonstore/domain/notification/service/NotificationService.java
  src/main/java/deepdive/jsonstore/domain/notification/service/NotificationValidationService.java
  src/main/resources/static/firebase-messaging-sw.js
  src/main/resources/static/index.html
  src/main/resources/static/js/register-token.js
  src/main/resources/static/js/send-notification.js
  src/test/java/deepdive/jsonstore/domain/notification/controller/NotificationApiControllerTest.java
  src/test/java/deepdive/jsonstore/domain/notification/service/NotificationServiceTest.java
  src/test/java/deepdive/jsonstore/domain/notification/service/NotificationValidationServiceTest.java
Labels: 💫 feat, ♻️ refactor, ✅ test

#76 feat: 알림 내역 조회 기능 추가
  build.gradle
  src/main/java/deepdive/jsonstore/domain/notification/controller/NotificationApiController.java
  src/main/java/deepdive/jsonstore/domain/notification/dto/NotificationHistoryRequest.java
  src/main/java/deepdive/jsonstore/domain/notification/repository/NotificationRepository.java
  src/main/java/deepdive/jsonstore/domain/notification/service/NotificationService.java
  src/main/resources/application-dev.yml
  src/main/resources/static/js/history-fetcher.js
  src/test/java/deepdive/jsonstore/domain/notification/controller/NotificationApiControllerTest.java
  src/test/java/deepdive/jsonstore/domain/notification/service/NotificationServiceTest.java
Labels: 💫 feat, ♻️ refactor, ✅ test
